name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Run Server
        run: |
          docker build -t hodu .
          docker run --privileged -dp 8080:8080 hodu
      - name: Install Test Cli
        run: |
          npm install -g @usebruno/cli
      - name: Run Tests
        working-directory: hodu-server/tests/bruno
        run: |
          bru run --tests-only --env local
