name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & Run Server
        run: |
          docker build -t hodu .
          docker run --privileged -dp 8080:8080 hodu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/wafflestudio/hodu:pr-${{ github.event.number }}

      - name: Install Test Cli
        run: |
          npm install -g @usebruno/cli

      - name: Run Tests
        working-directory: hodu-server/tests/bruno
        run: |
          bru run
