name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.*/**/*.md'
      - 'CODEOWNERS'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.*/**/*.md'
      - 'CODEOWNERS'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Run Server
        run: |
          docker build -t waffle-judge .
          docker run -d -p 8080:8080 waffle-judge
      - name: Install Test Cli
        run: |
          npm install -g @usebruno/cli
      - name: Run Tests
        working-directory: tests/bruno
        run: |
          bru run
